name = "TableTestSets"
uuid = "f9bf3ced-5811-49c3-be57-f5a2c1e23f47"
authors = ["Eric P. Hanson"]
version = "0.1.0"

[deps]
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
PrettyTables = "0.8"
Tables = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
